services:
  news_channel_app:
    container_name: news_channel_app
    build:
      context: .
      dockerfile: ./docker/backend/Dockerfile
    expose:
      - 9000
    volumes:
      - ./backend:/usr/src/app
      - ./backend/public:/usr/src/app/public
      - ./backend/storage/logs:/usr/src/app/storage/logs
    depends_on:
      - news_channel_db
    networks:
      - app_network
    environment:
      DB_CONNECTION: mysql
      DB_HOST: news_channel_db
      DB_PORT: 3306
      DB_DATABASE: news_channel
      DB_USERNAME: root
      DB_PASSWORD: root

  news_channel_nginx:
    container_name: news_channel_nginx
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    volumes:
      - ./backend/public:/usr/src/app/public
    ports:
      - 8000:80
    depends_on:
      - news_channel_app
    environment:
      NGINX_FPM_HOST: news_channel_app
      NGINX_ROOT: /usr/src/app/public
    networks:
      - app_network

  news_channel_db:
    container_name: news_channel_db
    restart: always
    build:
      context: .
      dockerfile: ./docker/db/Dockerfile
    volumes:
      - ./backend/storage/db-data:/var/lib/mysql
    ports:
      - 3308:3306
    environment:
      MYSQL_DATABASE: news_channel
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
    networks:
      - app_network

  news_channel_redis:
    container_name: news_channel_redis
    image: redis:latest
    ports:
      - 6380:6379
    networks:
      - app_network

  news_channel_frontend:
    container_name: news_channel_frontend
    build:
      context: .
      dockerfile: ./docker/frontend/Dockerfile
    ports:
      - "3000:3000"
    networks:
      - app_network
    volumes:
      - ./frontend:/usr/src/app
    depends_on:
      - news_channel_db
      - news_channel_app
    tty: true

networks:
  app_network:
    driver: bridge
